name: vox_pad
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  json_annotation: ^4.9.0
  marquee: ^2.2.3
  network_info_plus: ^5.0.3
  permission_handler: ^9.0.0
  multicast_dns: ^0.3.2+6
  connectivity_plus: ^2.0.2
  wifi_info_plugin_plus: ^2.0.2
  fluttertoast: ^8.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11  # Latest version

flutter:
  uses-material-design: true

  assets:
    - lib/res/

dependency_overrides:
  fading_edge_scrollview: ^4.1.1
